package constants

var (
	SELEFRADATABASEDSN                                           = "SELEFRA_DATABASE_DSN"
	Initprovidererrors                                           = "init provider error: %s"
	Providerpulltableerrors                                      = "provider pull table error: %s"
	Contextcanceled                                              = "context canceled"
	Analysisconfigerrs                                           = "analysis config err: %s"
	Newclientserrs                                               = "new clients err: %s"
	NA                                                           = "N/A"
	Notsupported                                                 = "not_supported"
	Apikeymustbeconfigured                                       = "api_key must be configured"
	Constants_3                                                  = ""
	Constants_4                                                  = ""
	Errors                                                       = "errors"
	Strings                                                      = "strings"
	Selefra                                                      = "Selefra"
	STRIPEAPIKEY                                                 = "STRIPE_API_KEY"
	Stripe                                                       = "stripe"
	Accountinformationnotfound                                   = "account information not found"
	Constants_1                                                  = "."
	Testing                                                      = "testing"
	Hostuserpostgrespasswordpassportdbnamepostgressslmodedisable = "host=127.0.0.1 user=postgres password=pass port=5432 dbname=postgres sslmode=disable"
	Constants_2                                                  = "*"
	Context                                                      = "context"
	V                                                            = "v0.0.1"
	Constants_0                                                  = ""
	Os                                                           = "os"
)
