package tables

import (
	"context"

	"github.com/selefra/selefra-provider-sdk/provider/schema"
	"github.com/selefra/selefra-provider-sdk/provider/transformer/column_value_extractor"
	"github.com/selefra/selefra-provider-sdk/table_schema_generator"
	"github.com/selefra/selefra-provider-stripe/stripe_client"
	"github.com/stripe/stripe-go"
)

type TableStripeSubscriptionGenerator struct {
}

var _ table_schema_generator.TableSchemaGenerator = &TableStripeSubscriptionGenerator{}

func (x *TableStripeSubscriptionGenerator) GetTableName() string {
	return "stripe_subscription"
}

func (x *TableStripeSubscriptionGenerator) GetTableDescription() string {
	return ""
}

func (x *TableStripeSubscriptionGenerator) GetVersion() uint64 {
	return 0
}

func (x *TableStripeSubscriptionGenerator) GetOptions() *schema.TableOptions {
	return &schema.TableOptions{}
}

func (x *TableStripeSubscriptionGenerator) GetDataSource() *schema.DataSource {
	return &schema.DataSource{
		Pull: func(ctx context.Context, clientMeta *schema.ClientMeta, taskClient any, task *schema.DataSourcePullTask, resultChannel chan<- any) *schema.Diagnostics {

			conn, err := stripe_client.Connect(ctx, taskClient.(*stripe_client.Client).Config)
			if err != nil {

				return schema.NewDiagnosticsErrorPullTable(task.Table, err)
			}

			params := &stripe.SubscriptionListParams{
				ListParams: stripe.ListParams{
					Context: ctx,
					Limit:   stripe.Int64(100),
				},
			}

			var count int64
			i := conn.Subscriptions.List(params)
			for i.Next() {
				resultChannel <- i.Subscription()
				count++

			}
			if err := i.Err(); err != nil {

				return schema.NewDiagnosticsErrorPullTable(task.Table, err)
			}

			return schema.NewDiagnosticsErrorPullTable(task.Table, nil)

		},
	}
}

func (x *TableStripeSubscriptionGenerator) GetExpandClientTask() func(ctx context.Context, clientMeta *schema.ClientMeta, taskClient any, task *schema.DataSourcePullTask) []*schema.ClientTaskContext {
	return nil
}

func (x *TableStripeSubscriptionGenerator) GetColumns() []*schema.Column {
	return []*schema.Column{
		table_schema_generator.NewColumnBuilder().ColumnName("billing_cycle_anchor").ColumnType(schema.ColumnTypeTimestamp).Description("Determines the date of the first full invoice, and, for plans with month or year intervals, the day of the month for subsequent invoices.").
			Extractor(column_value_extractor.StructSelector("BillingCycleAnchor")).Build(),
		table_schema_generator.NewColumnBuilder().ColumnName("current_period_start").ColumnType(schema.ColumnTypeTimestamp).Description("Start of the current period that the subscription has been invoiced for.").
			Extractor(column_value_extractor.StructSelector("CurrentPeriodStart")).Build(),
		table_schema_generator.NewColumnBuilder().ColumnName("days_until_due").ColumnType(schema.ColumnTypeInt).Description("Number of days a customer has to pay invoices generated by this subscription. This value will be null for subscriptions where collection_method=charge_automatically.").
			Extractor(column_value_extractor.StructSelector("DaysUntilDue")).Build(),
		table_schema_generator.NewColumnBuilder().ColumnName("default_payment_method").ColumnType(schema.ColumnTypeJSON).Description("ID of the default payment method for the subscription. It must belong to the customer associated with the subscription. This takes precedence over default_source. If neither are set, invoices will use the customer’s invoice_settings.default_payment_method or default_source.").Build(),
		table_schema_generator.NewColumnBuilder().ColumnName("metadata").ColumnType(schema.ColumnTypeJSON).Description("Set of key-value pairs that you can attach to an subscription. This can be useful for storing additional information about the subscription in a structured format.").Build(),
		table_schema_generator.NewColumnBuilder().ColumnName("pending_update").ColumnType(schema.ColumnTypeJSON).Description("If specified, pending updates that will be applied to the subscription once the latest_invoice has been paid.").Build(),
		table_schema_generator.NewColumnBuilder().ColumnName("schedule").ColumnType(schema.ColumnTypeJSON).Description("The schedule attached to the subscription.").Build(),
		table_schema_generator.NewColumnBuilder().ColumnName("trial_start").ColumnType(schema.ColumnTypeTimestamp).Description("If the subscription has a trial, the start of that trial.").
			Extractor(column_value_extractor.StructSelector("TrialStart")).Build(),
		table_schema_generator.NewColumnBuilder().ColumnName("customer_id").ColumnType(schema.ColumnTypeString).Description("ID of the customer who owns the subscription.").
			Extractor(column_value_extractor.StructSelector("Customer.ID")).Build(),
		table_schema_generator.NewColumnBuilder().ColumnName("status").ColumnType(schema.ColumnTypeString).Description("Possible values are incomplete, incomplete_expired, trialing, active, past_due, canceled, or unpaid.").Build(),
		table_schema_generator.NewColumnBuilder().ColumnName("collection_method").ColumnType(schema.ColumnTypeString).Description("Either charge_automatically, or send_invoice. When charging automatically, Stripe will attempt to pay this subscription at the end of the cycle using the default source attached to the customer. When sending an invoice, Stripe will email your customer an invoice with payment instructions.").Build(),
		table_schema_generator.NewColumnBuilder().ColumnName("current_period_end").ColumnType(schema.ColumnTypeTimestamp).Description("End of the current period that the subscription has been invoiced for. At the end of this period, a new invoice will be created.").
			Extractor(column_value_extractor.StructSelector("CurrentPeriodEnd")).Build(),
		table_schema_generator.NewColumnBuilder().ColumnName("pending_invoice_item_interval").ColumnType(schema.ColumnTypeJSON).Description("Specifies an interval for how often to bill for any pending invoice items. It is analogous to calling Create an invoice for the given subscription at the specified interval.").Build(),
		table_schema_generator.NewColumnBuilder().ColumnName("canceled_at").ColumnType(schema.ColumnTypeTimestamp).Description("If the subscription has been canceled, the date of that cancellation. If the subscription was canceled with cancel_at_period_end, canceled_at will reflect the time of the most recent update request, not the end of the subscription period when the subscription is automatically moved to a canceled state.").
			Extractor(column_value_extractor.StructSelector("CanceledAt")).Build(),
		table_schema_generator.NewColumnBuilder().ColumnName("created").ColumnType(schema.ColumnTypeTimestamp).Description("Time at which the subscription was created.").
			Extractor(column_value_extractor.StructSelector("Created")).Build(),
		table_schema_generator.NewColumnBuilder().ColumnName("default_tax_rates").ColumnType(schema.ColumnTypeJSON).Description("The tax rates that will apply to any subscription item that does not have tax_rates set. Invoices created will have their default_tax_rates populated from the subscription.").Build(),
		table_schema_generator.NewColumnBuilder().ColumnName("pause_collection").ColumnType(schema.ColumnTypeJSON).Description("If specified, payment collection for this subscription will be paused.").Build(),
		table_schema_generator.NewColumnBuilder().ColumnName("billing_thresholds").ColumnType(schema.ColumnTypeJSON).Description("Define thresholds at which an invoice will be sent, and the subscription advanced to a new billing period.").Build(),
		table_schema_generator.NewColumnBuilder().ColumnName("livemode").ColumnType(schema.ColumnTypeBool).Description("Has the value true if the subscription exists in live mode or the value false if the subscription exists in test mode.").Build(),
		table_schema_generator.NewColumnBuilder().ColumnName("pending_setup_intent").ColumnType(schema.ColumnTypeString).Description("You can use this SetupIntent to collect user authentication when creating a subscription without immediate payment or updating a subscription’s payment method, allowing you to optimize for off-session payments. Learn more in the SCA Migration Guide.").Build(),
		table_schema_generator.NewColumnBuilder().ColumnName("transfer_data").ColumnType(schema.ColumnTypeJSON).Description("The account (if any) the subscription’s payments will be attributed to for tax reporting, and where funds from each payment will be transferred to for each of the subscription’s invoices.").Build(),
		table_schema_generator.NewColumnBuilder().ColumnName("cancel_at_period_end").ColumnType(schema.ColumnTypeBool).Description("If the subscription has been canceled with the at_period_end flag set to true, cancel_at_period_end on the subscription will be true. You can use this attribute to determine whether a subscription that has a status of active is scheduled to be canceled at the end of the current period.").Build(),
		table_schema_generator.NewColumnBuilder().ColumnName("default_source").ColumnType(schema.ColumnTypeJSON).Description("ID of the default payment source for the subscription. It must belong to the customer associated with the subscription and be in a chargeable state. If default_payment_method is also set, default_payment_method will take precedence. If neither are set, invoices will use the customer’s invoice_settings.default_payment_method or default_source.").Build(),
		table_schema_generator.NewColumnBuilder().ColumnName("latest_invoice_id").ColumnType(schema.ColumnTypeString).Description("ID of the most recent invoice this subscription has generated.").
			Extractor(column_value_extractor.StructSelector("LatestInvoice.ID")).Build(),
		table_schema_generator.NewColumnBuilder().ColumnName("start_date").ColumnType(schema.ColumnTypeTimestamp).Description("Date when the subscription was first created. The date might differ from the created date due to backdating.").
			Extractor(column_value_extractor.StructSelector("StartDate")).Build(),
		table_schema_generator.NewColumnBuilder().ColumnName("cancel_at").ColumnType(schema.ColumnTypeTimestamp).Description("A date in the future at which the subscription will automatically get canceled.").
			Extractor(column_value_extractor.StructSelector("CancelAt")).Build(),
		table_schema_generator.NewColumnBuilder().ColumnName("items").ColumnType(schema.ColumnTypeJSON).Description("List of subscription items, each with an attached price.").
			Extractor(column_value_extractor.StructSelector("Items.Data")).Build(),
		table_schema_generator.NewColumnBuilder().ColumnName("trial_end").ColumnType(schema.ColumnTypeTimestamp).Description("If the subscription has a trial, the end of that trial.").
			Extractor(column_value_extractor.StructSelector("TrialEnd")).Build(),
		table_schema_generator.NewColumnBuilder().ColumnName("ended_at").ColumnType(schema.ColumnTypeTimestamp).Description("If the subscription has ended, the date the subscription ended.").
			Extractor(column_value_extractor.StructSelector("EndedAt")).Build(),
		table_schema_generator.NewColumnBuilder().ColumnName("id").ColumnType(schema.ColumnTypeString).Description("Unique identifier for the subscription.").Build(),
		table_schema_generator.NewColumnBuilder().ColumnName("application_fee_percent").ColumnType(schema.ColumnTypeFloat).Description("A non-negative decimal between 0 and 100, with at most two decimal places. This represents the percentage of the subscription invoice subtotal that will be transferred to the application owner’s Stripe account.").
			Extractor(column_value_extractor.StructSelector("ApplicationFeePercent")).Build(),
		table_schema_generator.NewColumnBuilder().ColumnName("discount").ColumnType(schema.ColumnTypeJSON).Description("Describes the current discount applied to this subscription, if there is one. When billing, a discount applied to a subscription overrides a discount applied on a customer-wide basis.").Build(),
		table_schema_generator.NewColumnBuilder().ColumnName("next_pending_invoice_item_invoice").ColumnType(schema.ColumnTypeTimestamp).Description("Specifies the approximate timestamp on which any pending invoice items will be billed according to the schedule provided at pending_invoice_item_interval.").
			Extractor(column_value_extractor.StructSelector("EndedAt")).Build(),
	}
}

func (x *TableStripeSubscriptionGenerator) GetSubTables() []*schema.Table {
	return nil
}
